import SwiftUI

@main
struct SA_Inspector_001App: App {
    var body: some Scene {
        WindowGroup {
            VStack(spacing: 16) {
                Text("SA Inspector 001")
                    .font(.largeTitle)
                Text("Generated by Swifter.")
                Button("Start Inspection") {
                    print("Inspection started.")
                }
            }
            .padding()
            .frame(width: 700, height: 500)
        }
    }
}