import Foundation

@main
struct SwifterCLI {
    static func write(_ path: String, _ text: String) throws {
        let url = URL(fileURLWithPath: path)
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try text.write(to: url, atomically: true, encoding: .utf8)
    }

    static func main() throws {
        let args = Array(CommandLine.arguments.dropFirst())

        if args.count >= 3 && args[0] == "new" && args[1] == "swiftui-app" {
            let name = args.dropFirst(2).joined(separator: " ")
            let safe = name.replacingOccurrences(of: " ", with: "_")

            try write("\(safe)/Package.swift", """
            // swift-tools-version: 6.0
            import PackageDescription

            let package = Package(
                name: "\(safe)",
                platforms: [.macOS(.v15)],
                targets: [
                    .executableTarget(name: "\(safe)")
                ]
            )
            """)

            try write("\(safe)/Sources/\(safe)/main.swift", """
            import SwiftUI

            @main
            struct \(safe)App: App {
                var body: some Scene {
                    WindowGroup {
                        VStack(spacing: 16) {
                            Text("\(name)")
                                .font(.largeTitle)
                            Text("Generated by Swifter.")
                            Button("Start Inspection") {
                                print("Inspection started.")
                            }
                        }
                        .padding()
                        .frame(width: 700, height: 500)
                    }
                }
            }
            """)

            try write("\(safe)/SWIFTER_MANIFEST.json", """
            {
              "project": "\(name)",
              "safe_name": "\(safe)",
              "generated_by": "SwifterCLI",
              "type": "swiftui-app",
              "status": "swiftui_seed_created"
            }
            """)

            print("✅ Created SwiftUI app: \(safe)")
            print("Next: cd \(safe) && /usr/bin/xcrun swift run")
        } else {
            print("Usage: swifter new swiftui-app \"SA Inspector\"")
        }
    }
}
