import Foundation

@main
struct SwifterCLI {
    static func write(_ path: String, _ text: String) throws {
        let url = URL(fileURLWithPath: path)
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try text.write(to: url, atomically: true, encoding: .utf8)
    }

    static func main() throws {
        let args = Array(CommandLine.arguments.dropFirst())

        if args.count >= 3 && args[0] == "new" && args[1] == "app" {
            let name = args.dropFirst(2).joined(separator: " ")
            let safe = name.replacingOccurrences(of: " ", with: "_")

            try FileManager.default.createDirectory(atPath: safe, withIntermediateDirectories: true)

            try write("\(safe)/README.md", """
            # \(name)

            Generated by Swifter.

            Swift is the language.
            Swifter is the leverage layer.
            """)

            try write("\(safe)/SWIFTER_MANIFEST.json", """
            {
              "project": "\(name)",
              "safe_name": "\(safe)",
              "generated_by": "SwifterCLI",
              "status": "seed_created",
              "next": "Generate SwiftUI skeleton"
            }
            """)

            print("✅ Created \(safe)")
            print("✅ Added README.md")
            print("✅ Added SWIFTER_MANIFEST.json")
        } else {
            print("Usage: swifter new app \"SA Lite\"")
        }
    }
}
